# Generated by Django 4.2 on 2024-02-15 19:50

from django.db import migrations, models

import ip_consumer.custom_model_fileds


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IPAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    ip_consumer.custom_model_fileds.IPAddressField(
                        max_length=50, unique=True
                    ),
                ),
                ("info", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
